//export const ENDPOINT = 'https://127.0.0.1:8000/'
//export const ENDPOINT = 'https://192.168.137.1:8000/'
//export const ENDPOINT = 'http://volyvolt.us-east-2.elasticbeanstalk.com/'
export const ENDPOINT = 'https://volyvolt-back.osc-fr1.scalingo.io/'
//export const FRONTENDPOINT = 'http://localhost:3000/'
export const FRONTENDPOINT = 'https://volyvolt.org/'