/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/volyvolt3d/PowerVolyVolt.glb src/component/solution/volyvolt.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./volyvolt3d/PowerVolyVolt.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.275, 0]} rotation={[0, -0.505, 0]}>
        <group position={[0.095, -0.013, 0.021]} rotation={[0, 0, -Math.PI / 2]}>
          <group position={[0, 0.001, -0.001]} rotation={[2.182, 0, 0]}>
            <mesh geometry={nodes.Circle013.geometry} material={materials['Material.033']} />
            <mesh geometry={nodes.Circle013_1.geometry} material={materials['Material.017']} />
            <mesh geometry={nodes.Circle013_2.geometry} material={materials['Material.001']} />
          </group>
        </group>
        <mesh geometry={nodes.batterie_pleine.geometry} material={materials['batterie pleine']} position={[-0.1, 0.018, 0]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.026} />
        <group position={[0.093, -0.013, -0.025]} rotation={[-Math.PI / 2, 0, -3.134]}>
          <mesh geometry={nodes['Unbenannt-1'].geometry} material={materials['Unbenannt-1']} />
          <mesh geometry={nodes['Unbenannt-1_1'].geometry} material={materials['Unbenannt-1.R']} />
        </group>
        <mesh geometry={nodes.Plane001.geometry} material={materials.sy} position={[0.09, 0.025, 0]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes['Cw-Random-Label_Black_Bg008'].geometry} material={materials['label-6x18']} position={[-0.01, 0, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        </mesh>
        <mesh geometry={nodes.Plane002.geometry} material={materials.Plastic} position={[0.089, 0.025, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[1, 1.378, 1.378]} />
        <mesh geometry={nodes.Plane003.geometry} material={materials.sy} position={[-0.097, 0.018, 0]} />
        <mesh geometry={nodes.volivolt_white.geometry} material={materials['volivolt white']} position={[0, 0.004, 0.05]} scale={0.445} />
        <mesh geometry={nodes['volivolt-logo-alt-white_(1)'].geometry} material={materials['volivolt-logo-alt-white (1)']} position={[-0.07, 0.05, 0.001]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes['volivolt-logo-alt-white_(1)001'].geometry} material={materials['volivolt-logo-alt-white (1)']} position={[0.074, 0.05, 0.001]} rotation={[Math.PI, 0, Math.PI / 2]} />
        <group position={[0.093, -0.013, -0.023]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Куб002_1.geometry} material={materials['Metal.001']} />
          <mesh geometry={nodes.Куб002_2.geometry} material={materials['Plastic #1.001']} />
          <mesh geometry={nodes.Куб002_3.geometry} material={materials['Copper.001']} />
          <mesh geometry={nodes.Куб002_4.geometry} material={materials['Plastic #2.001']} />
        </group>
        <mesh geometry={nodes.Cube001.geometry} material={materials['sy.001']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['sy.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('./volyvolt3d/PowerVolyVolt.glb')
